server.port: 8080
server:
  request:
    useTempfile: true
    maxBodySize: 2mb
    maxFileSize: 500mb

solon.app:
  name: 'demo-app'
  group: 'demo'
  threads:
    virtual:
      enabled: true

solon.extend: "!db_ext"